Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████| 8/8 [00:39<00:00,  4.99s/it]
INFO:__main__:Tokenizer max length: 1000000000000000019884624838656
INFO:__main__:Loading datasets...
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    main(args)
  File "train.py", line 37, in main
    train_dataset, val_dataset = load_train_val_datasets(
  File "/home/llm4math/LLM-for-Math/Direct Verifier/code/data/dataset_loader.py", line 7, in load_train_val_datasets
    dataset = load_dataset('json', data_files=file_path, split='train')
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/datasets/load.py", line 1853, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/datasets/load.py", line 1556, in dataset_module_factory
    return PackagedDatasetModuleFactory(
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/datasets/load.py", line 942, in get_module
    data_files = DataFilesDict.from_patterns(
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/datasets/data_files.py", line 721, in from_patterns
    else DataFilesList.from_patterns(
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/datasets/data_files.py", line 624, in from_patterns
    resolve_pattern(
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/datasets/data_files.py", line 411, in resolve_pattern
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/home/llm4math/LLM-for-Math/Direct Verifier/code/../../data/data/verification_results_MATH_Mistral_L_flattened.jsonl'
