INFO:__main__:Loading model from ./results/final_model
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 12.24it/s]
INFO:__main__:Loading test data from ../../inference_results.jsonl
INFO:__main__:Number of test samples: 1
Inference:   0%|                                                                                               | 0/1 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "/home/llm4math/LLM-for-Math/Direct Verifier/code/infer.py", line 140, in <module>
    main(args)
  File "/home/llm4math/LLM-for-Math/Direct Verifier/code/infer.py", line 110, in main
    average_score, generated_texts = perform_inference(
                                     ^^^^^^^^^^^^^^^^^^
  File "/home/llm4math/LLM-for-Math/Direct Verifier/code/infer.py", line 39, in perform_inference
    generated_texts = tokenizer.batch_decode(outputs.sequences, skip_special_tokens=True)
                                             ^^^^^^^^^^^^^^^^^
AttributeError: 'Tensor' object has no attribute 'sequences'
